### PR TITLE
feat: use docker entrypoint

### PR DESCRIPTION
**Pull request by evantill**
fixes issue #12

BREAKING CHANGE: wrapping  script are simplified but not compatible with previous version

### CODE REVIEW

**Comment by evantill** [comment]
Hi, any update on this PR please ? You can close it if you are not interested by merging it

**Comment by woile** [comment]
I think we can merge it, could you add a migration guide to the commit message? thanks!

**Comment by evantill** [comment]
I have updated the usage examples in the README.md accordingly

**Comment by evantill** [comment]
see https://github.com/commitizen-tools/commitizen-docker-image/pull/13/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by woile** [comment]
I don't think that's enough, because that's how to use it **now**.

This change will probably break some people's code, I'd like them to come to the README to see what happened, and see a solution right away, a "miration guide", where they realize they only need to chnage a few things to mitigate the impact.

I think something as simple as:

```md
## Migration guide

We've moved this images from using `CMD` to `ENTRYPOINT`.

Where you were doing this:

docker run --rm --name commitizen registry.hub.docker.com/commitizen/commitizen:2 /bin/sh -c "cz ls"

Now you only need to do:

docker run --rm --name commitizen registry.hub.docker.com/commitizen/commitizen:2 ls
```

What do you think?

**Comment by woile** [comment]
While reviewing the docs, I noticed that [for Jenkins](https://commitizen-tools.github.io/commitizen/tutorials/jenkins_pipeline/) we run the command inside a docker image:

```groovy
useCz {
   sh "cz bump --changelog"
}
```

The `useCz` internally uses **this** docker image. Now, this is good, because teams can put the `cz bump` inside a Makefile, and they can still do:

```groovy
useCz {
   sh "make bump"
}
```

Which has the benefit of working also locally.

How would people achieve the same with this PR?

**Comment by evantill** [comment]
Not sure to understand the question.

```
useCz {
   sh "cz bump --changelog"
}
```

use the method 
```
def useCz(String authorName = 'Jenkins CI Server', String authorEmail = 'your-jenkins@email.com', String image =  'registry.hub.docker.com/commitizen/commitizen:latest', Closure body) {
    docker
    .image(image)
    .inside("-u 0 -v $WORKSPACE:/workspace -w /workspace -e GIT_AUTHOR_NAME='${authorName}' -e GIT_AUTHOR_EMAIL='${authorEmail}'") {
        sh "git config --global user.email '${authorName}'"
        sh "git config --global user.name '${authorEmail}'"
        body()
    }
}
```

so this is equivalent to 
```
  docker
    .image(image)
    .inside("-u 0 -v $WORKSPACE:/workspace -w /workspace -e GIT_AUTHOR_NAME='${authorName}' -e GIT_AUTHOR_EMAIL='${authorEmail}'") {
        sh "git config --global user.email '${authorName}'"
        sh "git config --global user.name '${authorEmail}'"
        sh "cz bump --changelog"
```

**Comment by evantill** [comment]
As explained in the updated readme, we can override the entrypoint using `--entrypoint /bin/sh`. This could be the change needed in jenkins script.

```bash
docker run --rm -it \
  --entrypoint /bin/sh \
  -v $(pwd):/app \
  commitizen/commitizen:latest
```

**Comment by evantill** [comment]
see https://issues.jenkins.io/browse/JENKINS-51307 for passing the entrypoint in the docker pipeline:

```js
customImage.inside("-u root --entrypoint='/start.sh'") {}
```

in this case the update should be _(see the end of the line `.inside()`)_
```
def useCz(String authorName = 'Jenkins CI Server', String authorEmail = 'your-jenkins@email.com', String image =  'registry.hub.docker.com/commitizen/commitizen:latest', Closure body) {
    docker
    .image(image)
    .inside("-u 0 -v $WORKSPACE:/workspace -w /workspace -e GIT_AUTHOR_NAME='${authorName}' -e GIT_AUTHOR_EMAIL='${authorEmail}' -entrypoint='/bin/sh'") {
        sh "git config --global user.email '${authorName}'"
        sh "git config --global user.name '${authorEmail}'"
        body()
    }
}
```

**Comment by woile** [comment]
Thanks. I'll merge it soon.

This breaking change will be part of commitizen `v3` release.

**Comment by woile** [comment]
Could you please rebase? Thanks!

**Comment by evantill** [comment]
done

**Pull request merged**
